name: "Lampac (NextGen)"
version: "1.02.0"
slug: "lampac_nextgen"
description: "Lampac – прокси для видео, торрентов, IPTV и DLNA (docker-совместимый)"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
host_network: true
ports:
  9118/tcp: 9118
ports_description:
  9118/tcp: "Веб-интерфейс"
map:
  - "config:rw"
  - "share:rw"
  - "media:rw"
options:
  root_password: "changeme"
schema:
  root_password: "str"
